excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://oasissublimation.github.io
title: Oasis Sublimation
email: oasissublimation2014@gmail.com
author: Oasis Sublimation
description: Wholesale Sublimation Clothing Manufacturer
paginate: 7
google_analytics: 
theme: jekyll-theme-hacker